import xmlrpc.client
import requests
import base64
import smtplib
import os
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

print("Simple test for CH-625 dining chair")

ODOO_URL = os.environ.get("ODOO_URL")
ODOO_DB = os.environ.get("ODOO_DB")
ODOO_USER = os.environ.get("ODOO_USER")
ODOO_PASSWORD = os.environ.get("ODOO_PASSWORD")

SMTP_HOST = os.environ.get("SMTP_HOST")
SMTP_PORT = int(os.environ.get("SMTP_PORT", 587))
SMTP_USER = os.environ.get("SMTP_USER")
SMTP_PASSWORD = os.environ.get("SMTP_PASSWORD")
SMTP_FROM = os.environ.get("SMTP_FROM")
SMTP_TO = os.environ.get("SMTP_TO")

# Connect to Odoo
common = xmlrpc.client.ServerProxy(f"{ODOO_URL}/xmlrpc/2/common")
uid = common.authenticate(ODOO_DB, ODOO_USER, ODOO_PASSWORD, {})
models = xmlrpc.client.ServerProxy(f"{ODOO_URL}/xmlrpc/2/object")

# Find product by name
product_ids = models.execute_kw(ODOO_DB, uid, ODOO_PASSWORD, 'product.product', 'search',
    [[['name', 'ilike', 'CH-625']]], {'limit': 1})
if not product_ids:
    print("Product not found")
    exit(1)

pid = product_ids[0]

# Fetch image
url = f"{ODOO_URL}/web/image/product.product/{pid}/image_128"
session = requests.Session()
session.auth = (ODOO_USER, ODOO_PASSWORD)
resp = session.get(url, timeout=10)

if resp.status_code == 200 and len(resp.content) > 100:
    b64 = base64.b64encode(resp.content).decode('utf-8')
    img_src = f"data:image/png;base64,{b64}"
    print("Image fetched, size:", len(resp.content))
else:
    img_src = ""
    print("No image found")

# Build email HTML as a simple string
html = """<html><body><h2>Test Product</h2>
<img src="IMAGE_PLACEHOLDER" style="width:100px;"/>
<p>If you see an image, the script works.</p>
</body></html>""".replace("IMAGE_PLACEHOLDER", img_src)

# Send email
msg = MIMEMultipart("alternative")
msg["Subject"] = "Test Image for CH-625"
msg["From"] = SMTP_FROM
msg["To"] = SMTP_TO
msg.attach(MIMEText(html, "html"))

with smtplib.SMTP(SMTP_HOST, SMTP_PORT, timeout=30) as server:
    server.starttls()
    server.login(SMTP_USER, SMTP_PASSWORD)
    server.send_message(msg)

print("Email sent")      </thead>
      <tbody>{rows}</tbody>
    </table>
    <div style="padding:20px; text-align:center;">
      <p>If you see an image, the script works.</p>
    </div>
  </div>
</div>
"""

print("Sending email...", flush=True)
msg = MIMEMultipart("alternative")
msg["Subject"] = "Test: CH-625 dining chair image"
msg["From"] = SMTP_FROM
msg["To"] = SMTP_TO
msg.attach(MIMEText(full_html, "html"))

with smtplib.SMTP(SMTP_HOST, SMTP_PORT, timeout=30) as server:
    server.starttls()
    server.login(SMTP_USER, SMTP_PASSWORD)
    server.send_message(msg)

print("Email sent", flush=True)      <h1 style="color:#fff; margin:0;">Low Stock Alert (Top 10)</h1>
      <p style="color:#9ca3af;">Showing {len(quants_limited)} lowest-stock items out of {len(quants)} total.</p>
    </div>
    <table style="width:100%; border-collapse:collapse;">
      <thead>
        <tr style="background:#f8fafc; border-bottom:2px solid #e5e7eb;">
          <th style="padding:15px; text-align:center;">Image</th>
          <th style="padding:15px; text-align:left;">Product Name</th>
          <th style="padding:15px; text-align:left;">Location</th>
          <th style="padding:15px; text-align:center;">In Stock</th>
          <th style="padding:15px; text-align:center;">Reserved</th>
        </tr>
      </thead>
      <tbody>
        {rows}
      </tbody>
    </table>
    <div style="padding:20px 30px; background:#fefefe; border-top:1px solid #eee; text-align:right;">
      <p style="margin:0; font-size:12px; color:#9ca3af;">Generated by GitHub Actions</p>
    </div>
  </div>
</div>
"""

print(f"Sending email to {SMTP_TO}...", flush=True)
msg = MIMEMultipart("alternative")
msg["Subject"] = f"Low Stock Alert (Top 10) - {__import__('datetime').datetime.now().strftime('%Y-%m-%d')}"
msg["From"] = SMTP_FROM
msg["To"] = SMTP_TO
msg.attach(MIMEText(full_html, "html"))

for attempt in range(3):
    try:
        with smtplib.SMTP(SMTP_HOST, SMTP_PORT, timeout=30) as server:
            server.starttls()
            server.login(SMTP_USER, SMTP_PASSWORD)
            server.send_message(msg)
        print("Email sent successfully", flush=True)
        break
    except Exception as e:
        print(f"Attempt {attempt+1} failed: {e}", flush=True)
        if attempt < 2:
            time.sleep(10)
        else:
            raise
